import {
  DataByteKey,
  DataInt16Key,
  DataUint16Key,
  DataInt32Key,
  DataUint32Key,
  DataInt64Key,
  DataUint64Key,
  DataUint160Key,
  DataUint256Key,
  DataStringKey,
  DataVectorKey,
  DataByteVectorKey,
  DataInt32VectorKey,
  DataInt64VectorKey,
  DataCurrencyMapKey,
  DataRatingsKey,
  DataURLKey,
  DataTransferDestinationKey,
  UTXORefKey,
  CrossChainDataRefKey,
  EncryptionDescriptorKey,
  SaltedDataKey,
  DataDescriptorKey,
  SignatureDataKey,
  VectorUint256Key,
  MMRLinksKey,
  MMRDescriptorKey,
  TypeDefinitionKey,
  MultiMapKey,
  ContentMultiMapRemoveKey,
  ProfileMediaKey,
  ZMemoMessageKey,
  ZMemoSignatureKey,
  CurrencyStartNotarizationKey,
  VERUSPAY_INVOICE_VDXF_KEY,
  IDENTITY_UPDATE_REQUEST_VDXF_KEY,
  IDENTITY_UPDATE_RESPONSE_VDXF_KEY,
  IDENTITY_AUTH_SIG_VDXF_KEY,
  LOGIN_CONSENT_RESPONSE_SIG_VDXF_KEY,
  LOGIN_CONSENT_REQUEST_VDXF_KEY,
  LOGIN_CONSENT_RESPONSE_VDXF_KEY,
  LOGIN_CONSENT_CHALLENGE_VDXF_KEY,
  LOGIN_CONSENT_DECISION_VDXF_KEY,
  WALLET_VDXF_KEY,
  LOGIN_CONSENT_REDIRECT_VDXF_KEY,
  LOGIN_CONSENT_WEBHOOK_VDXF_KEY,
  LOGIN_CONSENT_CONTEXT_VDXF_KEY,
  LOGIN_CONSENT_ID_PROVISIONING_WEBHOOK_VDXF_KEY,
  ID_ADDRESS_VDXF_KEY,
  ID_SYSTEMID_VDXF_KEY,
  ID_FULLYQUALIFIEDNAME_VDXF_KEY,
  ID_PARENT_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_REQUEST_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_CHALLENGE_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_DECISION_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_RESPONSE_VDXF_KEY,
  LOGIN_CONSENT_PROVISIONING_RESULT_VDXF_KEY,
  IDENTITY_NAME_COMMITMENT_TXID,
  IDENTITY_REGISTRATION_TXID,
  IDENTITY_UPDATE_TXID,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGREQUIREDINFO,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGAPPROVAL,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_COMPLETE,
  LOGIN_CONSENT_PROVISIONING_RESULT_STATE_FAILED,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_NAMETAKEN,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_UNKNOWN,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_COMMIT_FAILED,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_CREATION_FAILED,
  LOGIN_CONSENT_PROVISIONING_ERROR_KEY_TRANSFER_FAILED,
  SIGNED_SESSION_OBJECT_DATA,
  SIGNED_SESSION_OBJECT,
  CURRENCY_ADDRESS,
  DATA_TYPE_STRING,
  DATA_TYPE_DEFINEDKEY,
  IDENTITY_CREDENTIAL,
  CredentialKey
} from 'verus-typescript-primitives';

const vdxfKeyLabelMap = new Map([
  [DataByteKey.vdxfid, { label: "byte", fqn: DataByteKey.qualifiedname.name }],
  [DataInt16Key.vdxfid, { label: "int16", fqn: DataInt16Key.qualifiedname.name }],
  [DataUint16Key.vdxfid, { label: "uint16", fqn: DataUint16Key.qualifiedname.name }],
  [DataInt32Key.vdxfid, { label: "int32", fqn: DataInt32Key.qualifiedname.name }],
  [DataUint32Key.vdxfid, { label: "uint32", fqn: DataUint32Key.qualifiedname.name }],
  [DataInt64Key.vdxfid, { label: "int64", fqn: DataInt64Key.qualifiedname.name }],
  [DataUint64Key.vdxfid, { label: "uint64", fqn: DataUint64Key.qualifiedname.name }],
  [DataUint160Key.vdxfid, { label: "uint160", fqn: DataUint160Key.qualifiedname.name }],
  [DataUint256Key.vdxfid, { label: "uint256", fqn: DataUint256Key.qualifiedname.name }],
  [DataStringKey.vdxfid, { label: "string", fqn: DataStringKey.qualifiedname.name }],
  [DataVectorKey.vdxfid, { label: "vector", fqn: DataVectorKey.qualifiedname.name }],
  [DataByteVectorKey.vdxfid, { label: "byte vector", fqn: DataByteVectorKey.qualifiedname.name }],
  [DataInt32VectorKey.vdxfid, { label: "int32 vector", fqn: DataInt32VectorKey.qualifiedname.name }],
  [DataInt64VectorKey.vdxfid, { label: "int64 vector", fqn: DataInt64VectorKey.qualifiedname.name }],
  [DataCurrencyMapKey.vdxfid, { label: "currency map", fqn: DataCurrencyMapKey.qualifiedname.name }],
  [DataRatingsKey.vdxfid, { label: "ratings", fqn: DataRatingsKey.qualifiedname.name }],
  [DataURLKey.vdxfid, { label: "url", fqn: DataURLKey.qualifiedname.name }],
  [DataTransferDestinationKey.vdxfid, { label: "transfer destination", fqn: DataTransferDestinationKey.qualifiedname.name }],
  [UTXORefKey.vdxfid, { label: "utxo ref", fqn: UTXORefKey.qualifiedname.name }],
  [CrossChainDataRefKey.vdxfid, { label: "cross chain data ref", fqn: CrossChainDataRefKey.qualifiedname.name }],
  [EncryptionDescriptorKey.vdxfid, { label: "encryption descriptor", fqn: EncryptionDescriptorKey.qualifiedname.name }],
  [SaltedDataKey.vdxfid, { label: "salted data", fqn: SaltedDataKey.qualifiedname.name }],
  [DataDescriptorKey.vdxfid, { label: "data descriptor", fqn: DataDescriptorKey.qualifiedname.name }],
  [SignatureDataKey.vdxfid, { label: "signature data", fqn: SignatureDataKey.qualifiedname.name }],
  [VectorUint256Key.vdxfid, { label: "vector uint256", fqn: VectorUint256Key.qualifiedname.name }],
  [MMRLinksKey.vdxfid, { label: "mmr links", fqn: MMRLinksKey.qualifiedname.name }],
  [MMRDescriptorKey.vdxfid, { label: "mmr descriptor", fqn: MMRDescriptorKey.qualifiedname.name }],
  [TypeDefinitionKey.vdxfid, { label: "type definition", fqn: TypeDefinitionKey.qualifiedname.name }],
  [MultiMapKey.vdxfid, { label: "multi map", fqn: MultiMapKey.qualifiedname.name }],
  [ContentMultiMapRemoveKey.vdxfid, { label: "content multi map remove", fqn: ContentMultiMapRemoveKey.qualifiedname.name }],
  [ProfileMediaKey.vdxfid, { label: "profile media", fqn: ProfileMediaKey.qualifiedname.name }],
  [ZMemoMessageKey.vdxfid, { label: "z memo message", fqn: ZMemoMessageKey.qualifiedname.name }],
  [ZMemoSignatureKey.vdxfid, { label: "z memo signature", fqn: ZMemoSignatureKey.qualifiedname.name }],
  [CurrencyStartNotarizationKey.vdxfid, { label: "currency start notarization", fqn: CurrencyStartNotarizationKey.qualifiedname.name }],
  [VERUSPAY_INVOICE_VDXF_KEY.vdxfid, { label: "veruspay invoice", fqn: VERUSPAY_INVOICE_VDXF_KEY.qualifiedname.name }],
  [IDENTITY_UPDATE_REQUEST_VDXF_KEY.vdxfid, { label: "identity update request", fqn: IDENTITY_UPDATE_REQUEST_VDXF_KEY.qualifiedname.name }],
  [IDENTITY_UPDATE_RESPONSE_VDXF_KEY.vdxfid, { label: "identity update response", fqn: IDENTITY_UPDATE_RESPONSE_VDXF_KEY.qualifiedname.name }],
  [IDENTITY_AUTH_SIG_VDXF_KEY.vdxfid, { label: "identity auth signature", fqn: IDENTITY_AUTH_SIG_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_RESPONSE_SIG_VDXF_KEY.vdxfid, { label: "login consent response signature", fqn: LOGIN_CONSENT_RESPONSE_SIG_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_REQUEST_VDXF_KEY.vdxfid, { label: "login consent request", fqn: LOGIN_CONSENT_REQUEST_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_RESPONSE_VDXF_KEY.vdxfid, { label: "login consent response", fqn: LOGIN_CONSENT_RESPONSE_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_CHALLENGE_VDXF_KEY.vdxfid, { label: "login consent challenge", fqn: LOGIN_CONSENT_CHALLENGE_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_DECISION_VDXF_KEY.vdxfid, { label: "login consent decision", fqn: LOGIN_CONSENT_DECISION_VDXF_KEY.qualifiedname.name }],
  [WALLET_VDXF_KEY.vdxfid, { label: "wallet", fqn: WALLET_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_REDIRECT_VDXF_KEY.vdxfid, { label: "login consent redirect", fqn: LOGIN_CONSENT_REDIRECT_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_WEBHOOK_VDXF_KEY.vdxfid, { label: "login consent webhook", fqn: LOGIN_CONSENT_WEBHOOK_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_CONTEXT_VDXF_KEY.vdxfid, { label: "login consent context", fqn: LOGIN_CONSENT_CONTEXT_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_ID_PROVISIONING_WEBHOOK_VDXF_KEY.vdxfid, { label: "login consent id provisioning webhook", fqn: LOGIN_CONSENT_ID_PROVISIONING_WEBHOOK_VDXF_KEY.qualifiedname.name }],
  [ID_ADDRESS_VDXF_KEY.vdxfid, { label: "id address", fqn: ID_ADDRESS_VDXF_KEY.qualifiedname.name }],
  [ID_SYSTEMID_VDXF_KEY.vdxfid, { label: "id system id", fqn: ID_SYSTEMID_VDXF_KEY.qualifiedname.name }],
  [ID_FULLYQUALIFIEDNAME_VDXF_KEY.vdxfid, { label: "id fully qualified name", fqn: ID_FULLYQUALIFIEDNAME_VDXF_KEY.qualifiedname.name }],
  [ID_PARENT_VDXF_KEY.vdxfid, { label: "id parent", fqn: ID_PARENT_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_REQUEST_VDXF_KEY.vdxfid, { label: "login consent provisioning request", fqn: LOGIN_CONSENT_PROVISIONING_REQUEST_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_CHALLENGE_VDXF_KEY.vdxfid, { label: "login consent provisioning challenge", fqn: LOGIN_CONSENT_PROVISIONING_CHALLENGE_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_DECISION_VDXF_KEY.vdxfid, { label: "login consent provisioning decision", fqn: LOGIN_CONSENT_PROVISIONING_DECISION_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_RESPONSE_VDXF_KEY.vdxfid, { label: "login consent provisioning response", fqn: LOGIN_CONSENT_PROVISIONING_RESPONSE_VDXF_KEY.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_RESULT_VDXF_KEY.vdxfid, { label: "login consent provisioning result", fqn: LOGIN_CONSENT_PROVISIONING_RESULT_VDXF_KEY.qualifiedname.name }],
  [IDENTITY_NAME_COMMITMENT_TXID.vdxfid, { label: "identity name commitment txid", fqn: IDENTITY_NAME_COMMITMENT_TXID.qualifiedname.name }],
  [IDENTITY_REGISTRATION_TXID.vdxfid, { label: "identity registration txid", fqn: IDENTITY_REGISTRATION_TXID.qualifiedname.name }],
  [IDENTITY_UPDATE_TXID.vdxfid, { label: "identity update txid", fqn: IDENTITY_UPDATE_TXID.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGREQUIREDINFO.vdxfid, { label: "provisioning result state pending required info", fqn: LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGREQUIREDINFO.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGAPPROVAL.vdxfid, { label: "provisioning result state pending approval", fqn: LOGIN_CONSENT_PROVISIONING_RESULT_STATE_PENDINGAPPROVAL.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_RESULT_STATE_COMPLETE.vdxfid, { label: "provisioning result state complete", fqn: LOGIN_CONSENT_PROVISIONING_RESULT_STATE_COMPLETE.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_RESULT_STATE_FAILED.vdxfid, { label: "provisioning result state failed", fqn: LOGIN_CONSENT_PROVISIONING_RESULT_STATE_FAILED.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_ERROR_KEY_NAMETAKEN.vdxfid, { label: "provisioning error name taken", fqn: LOGIN_CONSENT_PROVISIONING_ERROR_KEY_NAMETAKEN.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_ERROR_KEY_UNKNOWN.vdxfid, { label: "provisioning error unknown", fqn: LOGIN_CONSENT_PROVISIONING_ERROR_KEY_UNKNOWN.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_ERROR_KEY_COMMIT_FAILED.vdxfid, { label: "provisioning error commit failed", fqn: LOGIN_CONSENT_PROVISIONING_ERROR_KEY_COMMIT_FAILED.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_ERROR_KEY_CREATION_FAILED.vdxfid, { label: "provisioning error creation failed", fqn: LOGIN_CONSENT_PROVISIONING_ERROR_KEY_CREATION_FAILED.qualifiedname.name }],
  [LOGIN_CONSENT_PROVISIONING_ERROR_KEY_TRANSFER_FAILED.vdxfid, { label: "provisioning error transfer failed", fqn: LOGIN_CONSENT_PROVISIONING_ERROR_KEY_TRANSFER_FAILED.qualifiedname.name }],
  [SIGNED_SESSION_OBJECT_DATA.vdxfid, { label: "signed session object data", fqn: SIGNED_SESSION_OBJECT_DATA.qualifiedname.name }],
  [SIGNED_SESSION_OBJECT.vdxfid, { label: "signed session object", fqn: SIGNED_SESSION_OBJECT.qualifiedname.name }],
  [CURRENCY_ADDRESS.vdxfid, { label: "currency address", fqn: CURRENCY_ADDRESS.qualifiedname.name }],
  [DATA_TYPE_DEFINEDKEY.vdxfid, { label: "vdxf key definitions", fqn: DATA_TYPE_DEFINEDKEY.qualifiedname.name }],
  [IDENTITY_CREDENTIAL.vdxfid, { label: "identity credential", fqn: IDENTITY_CREDENTIAL.qualifiedname.name }],
  [CredentialKey.vdxfid, { label: "credential data", fqn: CredentialKey.qualifiedname.name }]
]);

export function getVDXFKeyLabel(key, nullOnMiss = false) {
  const entry = vdxfKeyLabelMap.get(key);
  if (entry != null) return entry.label;
  return nullOnMiss ? null : (key.substring(0, 4) + '...' + key.substring(key.length - 4));
}

export function getKnownVDXFKeyName(key) {
  const entry = vdxfKeyLabelMap.get(key);
  if (entry != null) return entry.fqn;
  return null;
}