export const LOGIN_CONSENT_INFO = 'LOGIN_CONSENT_INFO'
export const VERUSPAY_INVOICE_INFO = 'VERUSPAY_INVOICE_INFO'
export const IDENTITY_UPDATE_REQUEST_INFO = 'IDENTITY_UPDATE_REQUEST_INFO'
export const MAX_DEEPLINK_STRING_LENGTH = 2046