export const DLIGHT_PRIVATE_ADDRESSES = 'listaddresses'
export const DLIGHT_PRIVATE_BALANCES = 'getprivatebalance'
export const DLIGHT_PRIVATE_TRANSACTIONS = 'listprivatetransactions'
export const DLIGHT_INFO = 'getinfo'
export const DLIGHT_BLOCKCOUNT = 'getblockcount'