export const NOTIFICATION_TYPE_BASIC = 'NOTIFICATION_TYPE_BASIC'
export const NOTIFICATION_TYPE_NAVIGATION = 'NOTIFICATION_TYPE_NAVIGATION'
export const NOTIFICATION_TYPE_LOADING = 'NOTIFICATION_TYPE_LOADING'
export const NOTIFICATION_TYPE_DEEPLINK = 'NOTIFICATION_TYPE_DEEPLINK'