export const NOTIFICATION_TYPE_BASIC = 'NOTIFICATION_TYPE_BASIC'
export const NOTIFICATION_TYPE_NAVIGATION = 'NOTIFICATION_TYPE_NAVIGATION'
export const NOTIFICATION_TYPE_LOADING = 'NOTIFICATION_TYPE_LOADING'
export const NOTIFICATION_TYPE_DEEPLINK = 'NOTIFICATION_TYPE_DEEPLINK'

// notification Widget Constants

export const NOTIFICATION_TYPE_VERUSID_PENDING = 'NOTIFICATION_TYPE_VERUSID_PENDING'
export const NOTIFICATION_TYPE_ACKNOWLEDGED = 'NOTIFICATION_TYPE_ACKNOWLEDGED'
export const NOTIFICATION_TYPE_VERUSID_READY = 'NOTIFICATION_TYPE_VERUSID_READY'
export const NOTIFICATION_TYPE_ERROR = 'NOTIFICATION_TYPE_ERROR'

export const NOTIFICATION_MESSAGES = {
    [NOTIFICATION_TYPE_VERUSID_PENDING]: 'pending',
    [NOTIFICATION_TYPE_ACKNOWLEDGED]: 'acknowledged',
    [NOTIFICATION_TYPE_VERUSID_READY]: 'is ready',
    [NOTIFICATION_TYPE_ERROR]: 'has failed, please check'
}

