export const NOTIFICATION_TYPE_BASIC = 'NOTIFICATION_TYPE_BASIC'
export const NOTIFICATION_TYPE_NAVIGATION = 'NOTIFICATION_TYPE_NAVIGATION'
export const NOTIFICATION_TYPE_LOADING = 'NOTIFICATION_TYPE_LOADING'
export const NOTIFICATION_TYPE_DEEPLINK = 'NOTIFICATION_TYPE_DEEPLINK'

// notification Widget Constants

export const NOTIFICATION_TYPE_PENDING = 'NOTIFICATION_TYPE_PENDING'
export const NOTIFICATION_TYPE_ACKNOWLEDGED = 'NOTIFICATION_TYPE_ACKNOWLEDGED'
export const NOTIFICATION_TYPE_READY = 'NOTIFICATION_TYPE_READY'
export const NOTIFICATION_TYPE_ERROR = 'NOTIFICATION_TYPE_ERROR'

export const NOTIFICATION_MESSAGES = {
    [NOTIFICATION_TYPE_PENDING]: 'pending',
    [NOTIFICATION_TYPE_ACKNOWLEDGED]: 'acknowledged',
    [NOTIFICATION_TYPE_READY]: 'ready',
    [NOTIFICATION_TYPE_ERROR]: 'error'
    }

