export const SEND_MODAL = 'send_modal'

// Send field IDs
export const SEND_MODAL_TO_ADDRESS_FIELD = 'SEND_MODAL_TO_ADDRESS_FIELD'
export const SEND_MODAL_MEMO_FIELD = 'SEND_MODAL_MEMO_FIELD'
export const SEND_MODAL_AMOUNT_FIELD = 'SEND_MODAL_AMOUNT_FIELD'
export const SEND_MODAL_FROM_CURRENCY_FIELD = 'SEND_MODAL_FROM_CURRENCY_FIELD'
export const SEND_MODAL_TO_CURRENCY_FIELD = 'SEND_MODAL_TO_CURRENCY_FIELD'

// Send modal types 
export const TRADITIONAL_CRYPTO_SEND_MODAL = 'TRADITIONAL_CRYPTO_SEND_MODAL'
export const CONVERSION_SEND_MODAL = 'CONVERSION_SEND_MODAL'

// Form steps
export const SEND_MODAL_FORM_STEP_FORM = "SEND_MODAL_FORM_STEP_FORM"
export const SEND_MODAL_FORM_STEP_CONFIRM = "SEND_MODAL_FORM_STEP_CONFIRM"
export const SEND_MODAL_FORM_STEP_RESULT = "SEND_MODAL_FORM_STEP_RESULT"