export const SEND_MODAL = 'send_modal'

// Send field IDs
export const SEND_MODAL_TO_ADDRESS_FIELD = 'SEND_MODAL_TO_ADDRESS_FIELD'
export const SEND_MODAL_DESTINATION_FIELD = 'SEND_MODAL_DESTINATION_FIELD'
export const SEND_MODAL_SOURCE_FIELD = 'SEND_MODAL_SOURCE_FIELD'
export const SEND_MODAL_MEMO_FIELD = 'SEND_MODAL_MEMO_FIELD'
export const SEND_MODAL_AMOUNT_FIELD = 'SEND_MODAL_AMOUNT_FIELD'
export const SEND_MODAL_FROM_CURRENCY_FIELD = 'SEND_MODAL_FROM_CURRENCY_FIELD'
export const SEND_MODAL_TO_CURRENCY_FIELD = 'SEND_MODAL_TO_CURRENCY_FIELD'
export const SEND_MODAL_IDENTITY_TO_LINK_FIELD = 'SEND_MODAL_IDENTITY_TO_LINK_FIELD'
export const SEND_MODAL_IDENTITY_TO_PROVISION_FIELD = 'SEND_MODAL_IDENTITY_TO_PROVISION_FIELD'
export const SEND_MODAL_USER_TO_AUTHENTICATE = 'SEND_MODAL_USER_TO_AUTHENTICATE'
export const SEND_MODAL_USER_ALLOWLIST = 'SEND_MODAL_USER_ALLOWLIST'
export const SEND_MODAL_PBAAS_CURRENCY_TO_ADD_FIELD = 'SEND_MODAL_PBAAS_CURRENCY_TO_ADD_FIELD'
export const SEND_MODAL_CONVERTTO_FIELD = 'SEND_MODAL_CONVERTTO_FIELD'
export const SEND_MODAL_VIA_FIELD = 'SEND_MODAL_VIA_FIELD'
export const SEND_MODAL_EXPORTTO_FIELD = 'SEND_MODAL_EXPORTTO_FIELD'
export const SEND_MODAL_IS_PRECONVERT = 'SEND_MODAL_IS_PRECONVERT'
export const SEND_MODAL_PRICE_ESTIMATE = 'SEND_MODAL_PRICE_ESTIMATE'
export const SEND_MODAL_SHOW_CONVERTTO_FIELD = 'SEND_MODAL_SHOW_CONVERTTO_FIELD'
export const SEND_MODAL_SHOW_VIA_FIELD = 'SEND_MODAL_SHOW_VIA_FIELD'
export const SEND_MODAL_SHOW_EXPORTTO_FIELD = 'SEND_MODAL_SHOW_EXPORTTO_FIELD'
export const SEND_MODAL_ADVANCED_FORM = 'SEND_MODAL_ADVANCED_FORM'

// Send modal types 
export const TRADITIONAL_CRYPTO_SEND_MODAL = 'TRADITIONAL_CRYPTO_SEND_MODAL'
export const CONVERSION_SEND_MODAL = 'CONVERSION_SEND_MODAL'
export const WITHDRAW_SEND_MODAL = 'WITHDRAW_SEND_MODAL'
export const DEPOSIT_SEND_MODAL = 'DEPOSIT_SEND_MODAL'
export const LINK_IDENTITY_SEND_MODAL = 'LINK_IDENTITY_SEND_MODAL'
export const PROVISION_IDENTITY_SEND_MODAL = 'PROVISION_IDENTITY_SEND_MODAL'
export const AUTHENTICATE_USER_SEND_MODAL = 'AUTHENTICATE_USER_SEND_MODAL'
export const ADD_PBAAS_CURRENCY_MODAL = 'ADD_PBAAS_CURRENCY_MODAL'
export const CONVERT_OR_CROSS_CHAIN_SEND_MODAL = 'CONVERT_OR_CROSS_CHAIN_SEND_MODAL'

// Form steps
export const SEND_MODAL_FORM_STEP_FORM = "SEND_MODAL_FORM_STEP_FORM"
export const SEND_MODAL_FORM_STEP_CONFIRM = "SEND_MODAL_FORM_STEP_CONFIRM"
export const SEND_MODAL_FORM_STEP_RESULT = "SEND_MODAL_FORM_STEP_RESULT"