packages:
  - "."

nodeLinker: hoisted
blockExoticSubdeps: false
autoInstallPeers: false

overrides:
  word-wrap: "1.2.4"
  bs58check: "2.1.2"
  braces: "3.0.2"
  tar: "4.4.18"
  semver: "6.3.1"
  level-filesystem: "1.2.0"
  levelup: "4.1.0"
  mem: "5.1.1"
  handlebars: "4.7.7"
  elliptic: "6.6.1"
  yargs-parser: "13.1.2"
  minimist: "1.2.6"
  debug: "2.6.9"
  ini: "1.3.7"
  npm-user-validate: "1.0.1"
  y18n: "4.0.1"
  hosted-git-info: "3.0.8"
  ssri: "8.0.1"
  color-string: "1.5.5"
  hermes-engine: "0.10.0"
  logkitty: "0.7.1"
  node-notifier: "8.0.1"
  merge-deep: "3.0.3"
  metro: "0.71.0"
  metro-config: "0.71.0"
  css-what: "5.0.1"
  path-parse: "1.0.7"
  ansi-regex: "5.0.1"
  "@npmcli/arborist": "2.8.2"
  "@npmcli/git": "2.0.8"
  nth-check: "2.0.1"
  set-value: "4.0.1"
  tmpl: "1.0.5"
  ssh2: "1.4.0"
  jszip: "3.8.0"
  normalize-url: "4.5.1"
  glob-parent: "5.1.2"
  lodash: "4.17.21"
  react-native: "0.71.19"
  "@react-native-community/cli": "8.0.4"
  prompts: "2.4.2"
  node-fetch: "2.6.7"
  async: "2.6.4"
  follow-redirects: "1.15.4"
  json-schema: "0.4.0"
  lodash-es: "4.17.21"
  nanoid: "3.1.31"
  plist: "3.0.5"
  ramda: "0.27.2"
  shelljs: "0.8.5"
  shell-quote: "1.7.3"
  unset-value: "2.0.1"
  terser: "4.8.1"
  got: "11.8.5"
  simple-plist: "1.3.1"
  cross-fetch: "3.1.5"
  parse-link-header: "2.0.0"
  "@react-native-async-storage/async-storage@1.17.10": "1.17.10"
  json5: "2.2.2"
  qs: "6.5.3"
  ua-parser-js: "0.7.33"
  http-cache-semantics: "4.1.1"
  decode-uri-component: "0.2.2"
  "@sideway/formula": "3.0.1"
  "@babel/core": "7.25.7"
  blake2b-wasm: "git+https://github.com/VerusCoin/blake2b-wasm.git#a16070b30bb8d8aee670f0c69b642913eca79998"
  "@bitgo/blake2b-wasm": "git+https://github.com/VerusCoin/blake2b-wasm.git#a16070b30bb8d8aee670f0c69b642913eca79998"
  browserify-sign: "4.2.2"
  secp256k1: "3.8.1"
  form-data: "4.0.4"
  tiny-secp256k1: "1.1.7"
  pbkdf2: "3.1.3"
  brace-expansion: "1.1.12"
  base-x: "3.0.11"
  cipher-base: "1.0.5"
  sha.js: "2.4.12"
  fast-xml-parser: "4.5.4"
  minimatch: "3.1.4"
  glob: "7.2.3"
  js-yaml: "3.14.1"
  ajv: "6.14.0"
  micromatch: "4.0.8"
  cross-spawn: "6.0.6"
  axios: "1.13.5"
  bn.js: "4.12.3"
  "immutable@4.3.8": "4.3.8"

allowBuilds:
  react-native-verus@0.6.10: true
  react-native-vector-icons@8.1.0: true
  core-js-pure: true
  keccak: true
  react-native-elements: true
  secp256k1: true
