# Keep the existing native modules on the legacy architecture during this upgrade.
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

$dynamic_frameworks = [
  'react-native-verus',
  'MnemonicSwift',
  'React',
  'React-Core',
  'RCT-Folly',
  'boost-for-react-native',
  'DoubleConversion',
  'glog',
  'React-cxxreact',
  'React-jsinspector',
  'React-callinvoker',
  'React-runtimeexecutor',
  'React-jsi',
  'React-perflogger',
  'React-jsiexecutor',
  'Yoga',
  'React-RCTActionSheet',
  'React-RCTAnimation',
  'RCTTypeSafety',
  'FBLazyVector',
  'RCTRequired',
  'ReactCommon',
  'FBReactNativeSpec',
  'React-RCTBlob',
  'React-RCTNetwork',
  'React-RCTImage',
  'React-RCTLinking',
  'React-RCTSettings',
  'React-RCTText',
  'React-RCTVibration',
  'ZcashLightClientKit',
  'gRPC-Swift',
  'Logging',
  'SwiftNIO',
  'CNIOLinux',
  'CNIODarwin',
  'CNIOWindows',
  'SwiftNIOConcurrencyHelpers',
  'CNIOAtomics',
  'SwiftNIOHTTP2',
  'SwiftNIOHTTP1',
  'CNIOHTTPParser',
  'SwiftNIOTLS',
  'SwiftNIOHPACK',
  'SwiftNIOSSL',
  'CNIOBoringSSL',
  'CNIOBoringSSLShims',
  'SwiftNIOTransportServices',
  'SwiftNIOFoundationCompat',
  'CGRPCZlib',
  'SQLite.swift',
  'SwiftNIOCore',
  '_NIODataStructures',
  'SwiftNIOPosix',
  'SwiftNIOEmbedded',
  'boost',
  'fmt',
  'React-logger',
  'React-Codegen'
]

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  # 'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !$dynamic_frameworks.include?(pod.name)
      puts "Overriding the static_framework? method for #{pod.name}"
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

target 'verusmobile' do
  config = use_native_modules!
  use_modular_headers!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # RuntimeApple shares ReactCommon's header directory. Generating another
  # module map for it under use_modular_headers! redefines ReactCommon.
  pod 'React-RuntimeApple', :path => "#{config[:reactNativePath]}/ReactCommon/react/runtime/platform/ios", :modular_headers => false

  # Pods for Verus-Mobile
  pod 'MnemonicSwift', '~> 2.0.0'
  pod 'SwiftNIO', '2.40.0'
  pod 'CocoaAsyncSocket'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|

        if target.name.include?('RCT-Folly')
           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION=1'
        end

        config.build_settings['ENABLE_BITCODE'] = 'NO'

        # Some pods still declare older minimums that Xcode 27 rejects.
        deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if deployment_target.nil? || Gem::Version.new(deployment_target) < Gem::Version.new(min_ios_version_supported)
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
        end
      end
    end
  end
end
