require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$dynamic_frameworks = [
  'react-native-verus-light-client',
  'MnemonicSwift',
  'React', 
  'React-Core', 
  'RCT-Folly', 
  'boost-for-react-native', 
  'DoubleConversion', 
  'glog', 
  'React-cxxreact', 
  'React-jsinspector', 
  'React-callinvoker', 
  'React-runtimeexecutor', 
  'React-jsi', 
  'React-perflogger', 
  'React-jsiexecutor', 
  'Yoga', 
  'React-RCTActionSheet', 
  'React-RCTAnimation', 
  'RCTTypeSafety', 
  'FBLazyVector', 
  'RCTRequired', 
  'ReactCommon', 
  'FBReactNativeSpec', 
  'React-RCTBlob', 
  'React-RCTNetwork', 
  'React-RCTImage', 
  'React-RCTLinking', 
  'React-RCTSettings', 
  'React-RCTText', 
  'React-RCTVibration', 
  'ZcashLightClientKit', 
  'gRPC-Swift', 
  'Logging', 
  'SwiftNIO', 
  'CNIOLinux', 
  'CNIODarwin', 
  'CNIOWindows', 
  'SwiftNIOConcurrencyHelpers', 
  'CNIOAtomics', 
  'SwiftNIOHTTP2', 
  'SwiftNIOHTTP1', 
  'CNIOHTTPParser', 
  'SwiftNIOTLS', 
  'SwiftNIOHPACK', 
  'SwiftNIOSSL', 
  'CNIOBoringSSL', 
  'CNIOBoringSSLShims', 
  'SwiftNIOTransportServices', 
  'SwiftNIOFoundationCompat', 
  'SwiftProtobuf', 
  'CGRPCZlib',
  'SQLite.swift'
]

platform :ios, '13.0'

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !$dynamic_frameworks.include?(pod.name)
      puts "Overriding the static_framework? method for #{pod.name}"
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

target 'verusmobile' do
  config = use_native_modules!
  use_frameworks!
  permissions_path = '../node_modules/react-native-permissions/ios'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Pods for Verus-Mobile
  pod 'ZcashLightClientKit', :git => 'https://github.com/michaeltout/ZcashLightClientKit.git', :branch => '0.9.1', :testspecs => ['Tests']
  pod 'MnemonicSwift', '~> 2.0.0'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
  
        
        if target.name == 'ZcashLightClientKit'
           config.build_settings['ZCASH_NETWORK_ENVIRONMENT'] = ENV["ZCASH_NETWORK_ENVIRONMENT"]
        end
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end