const claims = (identityId) => ([
  {
    id: 'firstName',
    name: 'First Name',
    desc: '',
    parent_claims: ['birthDate'],
    child_claims: [],
    local_key: '',
    hidden: false,
    categoryId: `${identityId}-personalInformation`,
  },
  {
    id: 'lastName',
    name: 'Last Name',
    desc: '',
    parent_claims: ['birthDate'],
    child_claims: [],
    local_key: '',
    hidden: false,
    categoryId: `${identityId}-personalInformation`,
  },
  {
    id: 'birthDate',
    name: 'Birth Date',
    desc: '',
    parent_claims: [],
    child_claims: ['firstName', 'lastName'],
    local_key: '',
    hidden: false,
    categoryId: `${identityId}-personalInformation`,
  },
  {
    id: 'bloodType',
    name: 'Blood Type',
    desc: '',
    parent_claims: ['healthConditions'],
    child_claims: [],
    local_key: '',
    hidden: false,
    categoryId: `${identityId}-healthCare`,
  },
  {
    id: 'healthConditions',
    name: 'Health Conditions',
    desc: '',
    parent_claims: [],
    child_claims: ['bloodType'],
    local_key: '',
    hidden: false,
    categoryId: `${identityId}-healthCare`,
  },
  {
    id: 'university',
    name: 'University',
    desc: '',
    parent_claims: [],
    child_claims: [],
    local_key: '',
    hidden: true,
    categoryId: `${identityId}-education`,
  },
  {
    id: 'address',
    name: 'Address',
    desc: '',
    parent_claims: [],
    child_claims: [],
    local_key: '',
    hidden: false,
    categoryId: `${identityId}-housing`,
  },
]);

export default claims;
