import { v4 as uuidv4 } from 'uuid';

const generateClaims = (identityId) => ([
  {
    id: uuidv4(),
    name: 'First Name',
    desc: '',
    parentClaims: [`${identityId}-birthDate`],
    claimData:'Faris',
    childClaims: [],
    localKey: '',
    hidden: false,
    categoryId: 1,
    identityId,
  },
  {
    id: `${identityId}-lastName`,
    name: 'Last Name',
    desc: '',
    parentClaims: [`${identityId}-birthDate`],
    claimData:'Kunic',
    childClaims: [],
    localKey: '',
    hidden: false,
    categoryId: `${identityId}-personalInformation`,
  },
  {
    id: `${identityId}-birthDate`,
    name: 'Birth Date',
    desc: '',
    parentClaims: [],
    childClaims: [`${identityId}-firstName`, `${identityId}-lastName`],
    claimData:'db6166942ef4ee75a76a5ac02d95ab84',
    localKey: '',
    hidden: false,
    categoryId: `${identityId}-personalInformation`,
  },
  {
    id: `${identityId}-bloodType`,
    name: 'Blood Type',
    desc: '',
    parentClaims: [`${identityId}-healthConditions`],
    claimData:'A+',
    childClaims: [],
    localKey: '',
    hidden: false,
    categoryId: `${identityId}-healthCare`,
  },
  {
    id: `${identityId}-healthConditions`,
    name: 'Health Conditions',
    desc: '',
    parentClaims: [],
    claimData:'db6166942ef4ee75a76a5ac02d95ab84',
    childClaims: [`${identityId}-bloodType`],
    localKey: '',
    hidden: false,
    categoryId: `${identityId}-healthCare`,
  },
  {
    id: `${identityId}-university`,
    name: 'University',
    desc: '',
    parentClaims: [],
    claimData:'',
    childClaims: [],
    localKey: '',
    hidden: true,
    categoryId: `${identityId}-education`,
  },
  {
    id: `${identityId}-address`,
    name: 'Address',
    desc: '',
    parentClaims: [],
    claimData:'',
    childClaims: [],
    localKey: '',
    hidden: false,
    categoryId: `${identityId}-housing`,
  },
]);

export default generateClaims;
