import {StyleSheet} from 'react-native';
import Colors from '../../globals/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
  },
  header: {
    marginBottom: 16,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  loadingText: {
    color: '#666',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 16,
    textAlign: 'center',
  },
  passwordCard: {
    width: '100%',
    maxWidth: 340,
  },
  iconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    padding: 16,
    marginBottom: 12,
  },
  summaryTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#F7F9FB',
    borderRadius: 8,
    paddingVertical: 12,
  },
  summaryCount: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1A1A1A',
  },
  summaryLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  txidCard: {
    backgroundColor: '#F7F9FB',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  partialErrorText: {
    color: '#9A3412',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
  },
  txidHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 8,
  },
  txidLabel: {
    flex: 1,
    minWidth: 0,
    color: '#1A1A1A',
    fontSize: 13,
    fontWeight: '700',
  },
  txidActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 'auto',
  },
  txidValue: {
    color: '#555',
    fontSize: 12,
    lineHeight: 18,
  },
  explorerButtonContent: {
    height: 32,
    paddingHorizontal: 4,
  },
  explorerButtonLabel: {
    color: Colors.primaryColor,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'none',
  },
  systemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    marginBottom: 12,
    overflow: 'hidden',
  },
  systemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  systemTitle: {
    flex: 1,
    color: '#1A1A1A',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  systemAddress: {
    color: '#777',
    fontSize: 12,
    marginTop: 2,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  rowText: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    color: '#1A1A1A',
    fontSize: 14,
    fontWeight: '600',
  },
  rowSubtitle: {
    color: '#777',
    fontSize: 12,
    marginTop: 2,
  },
  rowWarningSubtitle: {
    color: '#9A3412',
    fontWeight: '600',
  },
  rowAmount: {
    color: '#1A1A1A',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 10,
    maxWidth: 120,
  },
  warningCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF7ED',
    borderColor: '#FED7AA',
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  warningText: {
    flex: 1,
    color: '#9A3412',
    fontSize: 13,
    lineHeight: 19,
    marginLeft: 8,
  },
  criticalWarningCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FEF2F2',
    borderColor: '#FCA5A5',
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  criticalWarningContent: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  criticalWarningTitle: {
    color: '#991B1B',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 6,
  },
  criticalWarningText: {
    color: '#991B1B',
    fontSize: 13,
    lineHeight: 19,
  },
  authorityLineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF7ED',
    borderColor: '#FED7AA',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 7,
    marginTop: 8,
  },
  authorityLineIcon: {
    marginRight: 7,
  },
  authorityLineText: {
    flex: 1,
    minWidth: 0,
  },
  authorityLineLabel: {
    color: '#9A3412',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 1,
  },
  authorityLineName: {
    color: '#7F1D1D',
    fontSize: 13,
    fontWeight: '800',
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F4F8FF',
    borderColor: '#D8E6FF',
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  infoText: {
    flex: 1,
    color: '#375A9E',
    fontSize: 13,
    lineHeight: 19,
    marginLeft: 8,
  },
  footer: {
    backgroundColor: '#FFFFFF',
    borderTopColor: '#E8E8E8',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  ctaCol: {
    flex: 1,
    minWidth: 0,
  },
  secondaryCta: {
    width: '100%',
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EBF6FF',
    borderWidth: 0,
    elevation: 0,
  },
  secondaryCtaContent: {
    height: 44,
  },
  secondaryCtaLabel: {
    color: Colors.primaryColor,
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0,
    textTransform: 'none',
  },
  primaryCta: {
    width: '100%',
    alignSelf: 'stretch',
    height: 44,
    borderRadius: 22,
  },
});
